#!/bin/bash
#
# Copyright 2013, Intel Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Library General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
# native
#
#Created on  06 fevr. 2014
#


UPSTREAM_SRC=${PWD}
TIZEN_DST=${PWD}/Tizen_Crosswalk
ROOTDIR=${PWD}

which svn > /dev/null || { echo "Subversion is not installed. Please install it before using this script." ; exit 1; }

# TODO: Check source directory presence

#mkdir -p ${UPSTREAM_SRC}
mkdir -p ${TIZEN_DST}

#Import the sources
#mkdir -p ${TIZEN_DST}/src
#rm -fr ${TIZEN_DST}/src/*

#cp -ra ${UPSTREAM_SRC}/src/* ${TIZEN_DST}/src/
##Clean git project
#find ${TIZEN_DST}/src -type d -name '.git' -exec rm -fr {} \;
#find ${TIZEN_DST}/src -type d -name '.gitignore' -exec rm -f {} \;
##Clean SVN project
#find ${TIZEN_DST}/src -type d -name '.svn' -exec rm -fr {} \;

echo "Prepare for push on Tizen.org : rsync process in progress..."
time rsync -a --delete --force --delete-excluded --exclude '.git*' --exclude '.svn' ${UPSTREAM_SRC}/src ${TIZEN_DST}
echo ""
echo "done."

#Import packging (gbs do not allow link.)
mkdir -p ${TIZEN_DST}/packaging
rm ${TIZEN_DST}/packaging/*
cp ${UPSTREAM_SRC}/src/xwalk/packaging/* ${TIZEN_DST}/packaging/
rm -f ${TIZEN_DST}/packaging/gbp*

# Display some informations:
echo "Source code as been duplicated in ${TIZEN_DST}. Here are some tips for next steps :"
echo ""
echo "First go to dest dir:"
echo "    cd ${TIZEN_DST}"
echo "You can see changes using:"
echo "    git status"
#echo "You can ask git to remove all file as upstream tree:"
#echo "    for all in \`git status | grep \"deleted:\" | cut -d ':' -f 2 - | sed 's/ //g'\`; do echo \$all; git rm \"\$all\"; done"
#echo "You can ask git to add all file as upstream tree:"
#echo "    git add *"
echo "You can stage all changes:"
echo "   git add -u"
echo "You can commit changes adding a message refering to upstream version:"
echo ""
[ -f ${TIZEN_DST}/src/xwalk/VERSION ] && cat ${TIZEN_DST}/src/xwalk/VERSION
echo ""
echo "   upstream commit-id in from github crosswalk.git: "
echo "Upstream version 5.34.92.0 --- TODO"
echo "   git commit -s"
echo ""
echo "Finally, you will be ready for push on GitHub:"
echo "  git push "
echo "Or on Tizen.org:"
echo "  git push origin HEAD:refs/for/master"

exit 0
#################################################################

